### PR TITLE
TWHL Tower and PDHLS Support + 3 other small mods

### PR DESCRIPTION
**Pull request by penperson**
Auto start and auto end for [Portal Done Half-Life Source](https://www.moddb.com/mods/portal-done-half-life-source/), [TWHL Tower: Source](https://www.moddb.com/mods/twhl-tower-source), [Antracide](https://www.runthinkshootlive.com/posts/antracide/), [Leon's Mappack 1](https://www.runthinkshootlive.com/posts/leons-mappack-1/) and [Simple_Etape](https://www.runthinkshootlive.com/posts/simple-etape/).

### CODE REVIEW

**Comment by thisis2838** [comment]
Can you remake this PR and merge it with develop instead?

**Comment by thekovic** [comment]
You can just click the Edit button next to the PR title and change the targetted branch from `master` to `develop`. No need to make a new PR entirely.

**Comment by penperson** [comment]
Hopefully that didn't break it

**Comment by thekovic** [comment]
It added some undesired commits to the PR. You should be able to get rid of them if you run rebase the branch history to develop. So a sequence of commands like this
```
git checkout develop
git fetch origin
git checkout master
git branch pen
git rebase develop
```
should work, hopefully.

**Pull request merged**
